# Generated by Django 4.1.4 on 2023-01-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birdle_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bird',
            name='image',
            field=models.URLField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='bird',
            name='name',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
